spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
    openfeign:
      circuitbreaker:
        enabled: false
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml, application/json  # 压缩类型
          min-request-size: 1024  # 最小压缩值标准，当数据大于 1024 才会进行压缩
        response:
          enabled: true
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 5000
      autoconfiguration:
        jackson:
          enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

resilience4j:
  timelimiter:
    instances:
      UserRpcgetUserByIdentifyString:
        timeoutDuration: 10s # 设置超时时间为2秒

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 8082

logging:
  level:
    com.mik.user.api: DEBUG
