spring:
  kafka:
    listener:
      type: batch
      ack-mode: manual
      concurrency: 3
    #    bootstrap-servers: b-1.kafka999.3pohcj.c4.kafka.eu-north-1.amazonaws.com:9092,b-2.kafka999.3pohcj.c4.kafka.eu-north-1.amazonaws.com:9092,b-3.kafka999.3pohcj.c4.kafka.eu-north-1.amazonaws.com:9092
    bootstrap-servers: 192.168.65.121:9092,192.168.65.121:9093,192.168.65.121:9094
    producer:
      batch-size: 16384
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 0
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: kehua
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 10

rocketmq:
  name-server: 192.168.68.114:9876
  producer:
    group: "g01"
  consumer:
    group: "kh38"
server:
  port: 8990
